#!/usr/bin/env python3

import sys

if __name__ == "__main__":
    wordArray = []
    argCount = len(sys.argv)
    for index in range(1, argCount):
        wordArray.append(sys.argv[index])
        wordArray.append(" ")

    print("got: \"{}\"".format(" ".join(wordArray)))
    result = ""
    for text in wordArray:
        for character in text:
            binary = ("{0:08b}").format(ord(character))
            result = result + binary + " "
    print("result is: {}".format(result))