#!/usr/bin/env python3

import sys

if __name__ == "__main__":

    wordList = []
    argCount = len(sys.argv)
    
    for index in range(1, argCount):
        wordList.append(sys.argv[index])
    
    result = ""

    for binary in wordList:
        character = chr(int(binary, 2))
        result = result + character
    
    print("result is: {}".format(result))